runtime: python39

env_variables:
  INSTANCE_CONNECTION_NAME: embee-accounting101:us-central1:cw-manager-db
  DB_USER: cwuser
  # DB_PASS is loaded from Google Secret Manager
  DB_NAME: cw_manager

beta_settings:
  cloud_sql_instances: embee-accounting101:us-central1:cw-manager-db

automatic_scaling:
  min_instances: 0
  max_instances: 10
