steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/$PROJECT_ID/casual-worker-manager:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/casual-worker-manager:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cw-manager-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/casual-worker-manager:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=embee-accounting101:us-central1:cw-manager-db,DB_USER=cwuser,DB_NAME=cw_manager,MASTER_ADMIN_EMAIL=markbmwape@gmail.com,RUN_MIGRATIONS_AT_STARTUP=true,GOOGLE_CLOUD_PROJECT=embee-accounting101'
      - '--add-cloudsql-instances'
      - 'embee-accounting101:us-central1:cw-manager-db'

images:
  - 'gcr.io/$PROJECT_ID/casual-worker-manager:latest' 